name: Copy config.json to Pages
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps & build
        run: |
          npm ci
          npm run pages:build
      - name: Copy config.json into output
        run: cp config.json .vercel/output/static/config.json
      - name: Deploy to Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: moontv-76m
          directory: .vercel/output/static
